name: Wave
version: 1.1.1
description: A reverse permissions plugin
author: Model_3
main: us.flowdesigns.wave.Wave
depend: [TotalFreedomMod]
commands:
  wave:
    usage: /<command> [reload | update]
    description: Shows information about or update Wave