name: Wave
version: ${project.version}
description: A reverse permissions plugin
author: Model_3
main: us.flowdesigns.wave.Wave
depend: [TotalFreedomMod]
api-version: 1.13
commands:
  wave:
    usage: /<command> [reload]
    description: Shows information about or reload Wave